### ISSUE TITLE
Making contact

### ISSUE THREAD

**Issue by lloyda** [HighEncryption/SyncPro#28]
Sorry to raise an issue, but can find no other way to make contact.

This looks like a very interesting project, that would fit a requirement I have. Is it available pre built anywhere?

**Comment by HighEncryption** [comment]
No problem. Sorry I didn't see it earlier.

Not at the moment, as I am still working through a lot of the missing features. That said, if you want to reply, I can start putting up alpha builds. I would love to hear any early feedback.

**Comment by lloyda** [comment]
Hi

Happy to look at an alpha version.

My use case is quite small.  Only OneDrive, and I’m generally happy with the sync that MS provide.  However, I want to sync back a copy (one way) to another location on the same PC, daily schedule is necessary. Presumably SyncPro will allow me to do this?

Lloyd

**Comment by HighEncryption** [comment]
Thanks Lloyd. At the moment only manual syncing works, however it shouldn't take much to get continuous and scheduled syncing working. Give me a day or so and I should have a build that you can try out.

**Comment by HighEncryption** [comment]
Also, you sent email to syncproapp@gmail.com to reach me directly (since Github doesn't seem to send email when a new issue is filed).

**Comment by HighEncryption** [comment]
The first release is published, so you can try out the bits now. 

https://github.com/HighEncryption/SyncPro/releases
